### ISSUE TITLE
Dynamic progressbar value

### ISSUE THREAD

**Issue by Grigorek** [aditbharadwaj/angular-gradient-progressbar#1]
Is there any option to dynamically change progress bar value?

**Comment by aditbharadwaj** [comment]
> Is there any option to dynamically change progress bar value?

as in dynamically moving the pointer to change the values ?

**Comment by Grigorek** [comment]
Yes, indeed. I was trying to change value with typescript, but pointer didnt move.

**Comment by aditbharadwaj** [comment]
> Yes, indeed. I was trying to change value with typescript, but pointer didnt move.

the pointer will only move if u change the [value] property inside the component 
`<angular-gradient-progressbar [type]="1" [value] ="YOURVALUE"]> </angular-gradient-progressbar>`
right now it defaults to 75 but u can change the value to ur specific custom value and it will change. the pointer is static it will only move to a specific position depending on the [value] provided.

**Comment by aditbharadwaj** [comment]
maybe if u can change ur values dynamically using different mean like a button and update the component using change detection then u can have the dynamic control over.
 in future release i might add a setting to have pointer dynamic to act as a dynamic scale progress bar to record value depending upon the position of the pointer. Pull request are always welcome. :)

**Comment by Grigorek** [comment]
Ok I get it, actually when I added ngOnChanges() to angular-gradient-progressbar.component.ts it started detecting changes so I draw progressbar again there

**Comment by aditbharadwaj** [comment]
> Ok I get it, actually when I added ngOnChanges() to angular-gradient-progressbar.component.ts it started detecting changes so I draw progressbar again there

indeed as i said if u can detect changes u can easily manipulate it dynamically. :) glad it worked.
