### ISSUE TITLE
Value 100 with default settings renders "medium" instead of "high"

### ISSUE THREAD

**Issue by ti8m-naegeli** [aditbharadwaj/angular-gradient-progressbar#33]
The following mark-up

```
<angular-gradient-progressbar [type]="1" [value]="100">
```

renders like this

![image](https://github.com/aditbharadwaj/angular-gradient-progressbar/assets/167068226/9a0d0d40-9100-4bef-9d82-7389c1ffb0e9)

I would expect the text to state "high", no?

**Comment by ti8m-naegeli** [comment]
After testing the logic in #34 here is my explanation for this behavior:

- Having seven bars (due to `barCount` defaulting to `7`) induces seven quartiles (`~ 14.29` % each)
- Because `quartileValueHigh` is being set to `7` anything above `quartileValueLow` (defaults to `4` = value `57.16`) to `7` = value `100` will be rendered as `medium`

For me those defaults feel counter-intuitive so I would the defaults to be either:

1. `barCount` to be `100` so `value < 40` will be `low` and `value < 70` will be `medium`
2. `quartileValueLow` to be `3` and `quartileValueHigh` to be `6` so `value < 42.87` will be `low` and `value < 85.74` will be `medium`

**Comment by aditbharadwaj** [comment]
Yes you are correct the default bar value heavily depends on the default quartileValueHigh. it can be changed but can also be improved for default use cases. 
Thanks @ti8m-naegeli  for the PR's, 
 will review them and merge it for the next release.
